/**
 * Autogenerated pgContext contract models and enums.
 */

export enum ContextCapability {
  SETUP = 'setup',
  DENSE_SEARCH = 'dense_search',
  POINT_SCROLL = 'point_scroll',
  COUNT = 'count',
  FACETS = 'facets',
  GROUPED_SEARCH = 'grouped_search',
  RECALL_CHECK = 'recall_check',
  TEXT_HYBRID = 'text_hybrid',
  GRAPH_FIRST = 'graph_first',
  VECTOR_FIRST = 'vector_first',
  RANK_FUSION = 'rank_fusion',
  JOINT = 'joint',
}

export enum ContextCollectionStatus {
  READY = 'ready',
  STALE = 'stale',
  FAILED = 'failed',
  DELETING = 'deleting',
}

export enum ContextDiagnosticCheckStatus {
  PASS = 'pass',
  WARNING = 'warning',
  FAIL = 'fail',
  SKIPPED = 'skipped',
}

export enum ContextDiagnosticStatus {
  HEALTHY = 'healthy',
  DEGRADED = 'degraded',
  BLOCKED = 'blocked',
}

export enum ContextFilterKind {
  COLUMN = 'column',
  JSONB_PATH = 'jsonb_path',
}

export enum ContextGraphDirection {
  OUT = 'out',
  IN = 'in',
  ANY = 'any',
  BOTH = 'both',
}

export enum ContextIndexKind {
  NONE = 'none',
  HNSW = 'hnsw',
}

export enum ContextIndexStatus {
  MISSING = 'missing',
  CREATING = 'creating',
  READY = 'ready',
  STALE = 'stale',
  FAILED = 'failed',
}

export enum ContextMetric {
  COSINE = 'cosine',
  INNER_PRODUCT = 'inner_product',
  L2 = 'l2',
  L1 = 'l1',
}

export enum ContextOnboardingStatus {
  UNASSESSED = 'unassessed',
  ELIGIBLE = 'eligible',
  DISMISSED = 'dismissed',
  COMPLETED = 'completed',
  INELIGIBLE = 'ineligible',
}

export enum ContextOperationKind {
  COLLECTION_CREATE = 'collection_create',
  COLLECTION_SET_DEFAULT = 'collection_set_default',
  COLLECTION_UPDATE = 'collection_update',
  COLLECTION_DELETE = 'collection_delete',
  COLLECTION_REINDEX = 'collection_reindex',
  VECTOR_ADD = 'vector_add',
  FILTER_ADD_COLUMN = 'filter_add_column',
  FILTER_ADD_JSONB_PATH = 'filter_add_jsonb_path',
  POINTS_UPSERT = 'points_upsert',
  POINTS_DELETE = 'points_delete',
  POINTS_RECONCILE = 'points_reconcile',
}

export enum ContextOperationStatus {
  QUEUED = 'queued',
  RUNNING = 'running',
  CANCEL_REQUESTED = 'cancel_requested',
  SUCCEEDED = 'succeeded',
  FAILED = 'failed',
  CANCELLED = 'cancelled',
}

export enum ContextPointReconciliationStatus {
  PENDING = 'pending',
  RECONCILING = 'reconciling',
  CURRENT = 'current',
  STALE = 'stale',
  FAILED = 'failed',
}

export enum ContextRankedMode {
  DENSE = 'dense',
  TEXT_HYBRID = 'text_hybrid',
  GRAPH_FIRST = 'graph_first',
  VECTOR_FIRST = 'vector_first',
  RANK_FUSION = 'rank_fusion',
  JOINT = 'joint',
}

export enum ContextRecallStatus {
  PASSING = 'passing',
  FAILING = 'failing',
  EMPTY_EXACT = 'empty_exact',
}

export enum ContextRecommendedAction {
  POINTS_RECONCILE = 'points_reconcile',
  COLLECTION_REINDEX = 'collection_reindex',
  REPAIR_SOURCE = 'repair_source',
  REPAIR_PERMISSIONS = 'repair_permissions',
  RECREATE_COLLECTION = 'recreate_collection',
  CONTACT_SUPPORT = 'contact_support',
}

export enum ContextScoreKind {
  CONTEXT_METRIC = 'context_metric',
  RRF = 'rrf',
  WEIGHTED_RRF = 'weighted_rrf',
  JOINT_WEIGHTED_RRF = 'joint_weighted_rrf',
}

export enum ContextServingStatus {
  AVAILABLE = 'available',
  BLOCKED = 'blocked',
}

export enum ContextSourceClassification {
  READY_TO_CONFIGURE = 'ready_to_configure',
  NEEDS_SETUP = 'needs_setup',
  UNSUPPORTED = 'unsupported',
  VECTOR_SOURCE = 'vector_source',
}

export enum ContextSourceMode {
  EXISTING = 'existing',
  ADD_COLUMN = 'add_column',
  NEW_TABLE = 'new_table',
}

export enum ContextVerificationCheckStatus {
  PASS = 'pass',
  FAIL = 'fail',
  SKIPPED = 'skipped',
}

export enum ContextErrorCode {
  REQUEST_INVALID = 'CONTEXT_REQUEST_INVALID',
  IDENTIFIER_INVALID = 'CONTEXT_IDENTIFIER_INVALID',
  SOURCE_INVALID = 'CONTEXT_SOURCE_INVALID',
  DELETE_CONFIRMATION_INVALID = 'CONTEXT_DELETE_CONFIRMATION_INVALID',
  POINT_KEY_INVALID = 'CONTEXT_POINT_KEY_INVALID',
  EMBEDDING_INVALID = 'CONTEXT_EMBEDDING_INVALID',
  FILTER_INVALID = 'CONTEXT_FILTER_INVALID',
  LIMIT_EXCEEDED = 'CONTEXT_LIMIT_EXCEEDED',
  GRAPH_START_REQUIRED = 'CONTEXT_GRAPH_START_REQUIRED',
  GRAPH_DIRECTION_INVALID = 'CONTEXT_GRAPH_DIRECTION_INVALID',
  RANKING_WEIGHTS_INVALID = 'CONTEXT_RANKING_WEIGHTS_INVALID',
  RESOURCE_NAMESPACE_MISMATCH = 'CONTEXT_RESOURCE_NAMESPACE_MISMATCH',
  COLLECTION_NOT_FOUND = 'CONTEXT_COLLECTION_NOT_FOUND',
  OPERATION_NOT_FOUND = 'CONTEXT_OPERATION_NOT_FOUND',
  COLLECTION_NOT_READY = 'CONTEXT_COLLECTION_NOT_READY',
  TEXT_COLUMN_REQUIRED = 'CONTEXT_TEXT_COLUMN_REQUIRED',
  GRAPH_NOT_READY = 'CONTEXT_GRAPH_NOT_READY',
  SOURCE_KEY_ALIGNMENT_INVALID = 'CONTEXT_SOURCE_KEY_ALIGNMENT_INVALID',
  CAPABILITY_UNAVAILABLE = 'CONTEXT_CAPABILITY_UNAVAILABLE',
  SOURCE_KEY_NOT_FOUND = 'CONTEXT_SOURCE_KEY_NOT_FOUND',
  SOURCE_VECTOR_INVALID = 'CONTEXT_SOURCE_VECTOR_INVALID',
  FILTER_REGISTRATION_CONFLICT = 'CONTEXT_FILTER_REGISTRATION_CONFLICT',
  POINT_CURSOR_INVALID = 'CONTEXT_POINT_CURSOR_INVALID',
  RECALL_UNAVAILABLE = 'CONTEXT_RECALL_UNAVAILABLE',
  COLLECTION_NAME_CONFLICT = 'CONTEXT_COLLECTION_NAME_CONFLICT',
  PREFLIGHT_BLOCKED = 'CONTEXT_PREFLIGHT_BLOCKED',
  OPERATION_CONFLICT = 'CONTEXT_OPERATION_CONFLICT',
  IDEMPOTENCY_CONFLICT = 'CONTEXT_IDEMPOTENCY_CONFLICT',
  OPERATION_NOT_CANCELLABLE = 'CONTEXT_OPERATION_NOT_CANCELLABLE',
  OPERATION_NOT_RETRYABLE = 'CONTEXT_OPERATION_NOT_RETRYABLE',
  OPERATION_CANCELLED = 'CONTEXT_OPERATION_CANCELLED',
  ONBOARDING_NOT_ELIGIBLE = 'CONTEXT_ONBOARDING_NOT_ELIGIBLE',
  ONBOARDING_NOT_AVAILABLE = 'CONTEXT_ONBOARDING_NOT_AVAILABLE',
  RUNTIME_UNSUPPORTED = 'CONTEXT_RUNTIME_UNSUPPORTED',
  EXTENSION_UNAVAILABLE = 'CONTEXT_EXTENSION_UNAVAILABLE',
  SOURCE_TABLE_UNSUPPORTED = 'CONTEXT_SOURCE_TABLE_UNSUPPORTED',
  SOURCE_KEY_REQUIRED = 'CONTEXT_SOURCE_KEY_REQUIRED',
  SOURCE_KEY_TYPE_UNSUPPORTED = 'CONTEXT_SOURCE_KEY_TYPE_UNSUPPORTED',
  SOURCE_KEY_TEXT_CONSTRAINT_REQUIRED = 'CONTEXT_SOURCE_KEY_TEXT_CONSTRAINT_REQUIRED',
  SOURCE_PRIVILEGE_REQUIRED = 'CONTEXT_SOURCE_PRIVILEGE_REQUIRED',
  VECTOR_COLUMN_MISSING = 'CONTEXT_VECTOR_COLUMN_MISSING',
  VECTOR_COLUMN_CONFLICT = 'CONTEXT_VECTOR_COLUMN_CONFLICT',
  VECTOR_TYPE_UNSUPPORTED = 'CONTEXT_VECTOR_TYPE_UNSUPPORTED',
  VECTOR_NULLABLE = 'CONTEXT_VECTOR_NULLABLE',
  VECTOR_DIMENSION_INVALID = 'CONTEXT_VECTOR_DIMENSION_INVALID',
  COSINE_ZERO_VECTOR = 'CONTEXT_COSINE_ZERO_VECTOR',
  RESULT_COLUMN_INVALID = 'CONTEXT_RESULT_COLUMN_INVALID',
  FILTER_COLUMN_INVALID = 'CONTEXT_FILTER_COLUMN_INVALID',
  JSONB_FILTER_PATH_INVALID = 'CONTEXT_JSONB_FILTER_PATH_INVALID',
  RESERVED_FILTER_CONFLICT = 'CONTEXT_RESERVED_FILTER_CONFLICT',
  TEXT_COLUMN_INVALID = 'CONTEXT_TEXT_COLUMN_INVALID',
  HNSW_UNSUPPORTED = 'CONTEXT_HNSW_UNSUPPORTED',
  INDEX_CONFLICT = 'CONTEXT_INDEX_CONFLICT',
  MEMORY_PRESSURE = 'CONTEXT_MEMORY_PRESSURE',
  PGVECTOR_SOURCE = 'CONTEXT_PGVECTOR_SOURCE',
  UNSUPPORTED_VECTOR_TYPE = 'CONTEXT_UNSUPPORTED_VECTOR_TYPE',
}

export interface ContextErrorDescriptor {
  status_code: number;
  message: string;
  safe_detail_fields: string[];
  retryable: boolean;
  conflict: boolean;
}

export interface ErrorBody {
  code: string;
  variant?: string | null;
  message: string;
  details: Record<string, any>;
}

export interface EmptyRequest {
}

export interface DiscoveryRequest {
  schema_names?: any;
}

export interface ContextSourceRequest {
  mode: ContextSourceMode;
  schema_name: string;
  table_name: string;
  source_key_column?: 'id';
  content_column?: any;
  metadata_column?: any;
}

export interface ContextVectorRequest {
  name?: any;
  column_name?: string;
  dimensions: number;
  metric?: ContextMetric;
}

export interface ContextVectorCreateRequest {
  name?: any;
  column_name?: string;
  dimensions: number;
  metric?: ContextMetric;
  mode?: 'existing' | 'add_column';
  index_kind?: ContextIndexKind;
  set_default?: boolean;
}

export interface JsonbFilterPathRequest {
  key: string;
  column: string;
  path: string[];
}

export interface CollectionCreateRequest {
  name: string;
  source: ContextSourceRequest;
  vector: ContextVectorRequest;
  text_column?: any;
  result_columns?: string[];
  filter_columns?: string[];
  jsonb_filter_paths?: JsonbFilterPathRequest[];
  index_kind?: ContextIndexKind;
  max_search_limit?: number;
}

export interface CollectionSetDefaultRequest {
  is_default: true;
}

export interface CollectionUpdateRequest {
  text_column?: any;
  result_columns?: any;
  max_search_limit?: any;
  default_vector_name?: any;
}

export interface CollectionDeleteRequest {
  confirm_collection_id: string;
}

export interface CollectionAliasRequest {
  alias_name: string;
  target_collection_name: string;
}

export interface CollectionLimitsRequest {
  strict_mode: boolean;
  max_dimensions?: any;
  max_vectors?: any;
  max_points?: any;
  max_filter_nodes?: any;
  max_search_limit?: any;
  max_candidate_budget?: any;
  query_timeout_ms?: any;
  max_index_memory_bytes?: any;
}

export interface VectorConfigureRequest {
  hnsw_options: Record<string, any>;
  quantization_options: Record<string, any>;
  status: 'ready' | 'building' | 'disabled' | 'failed';
}

export interface FilterColumnRequest {
  key: string;
  column: string;
}

export interface FilterJsonbPathRequest {
  key: string;
  column: string;
  path: string[];
}

export interface PointKeysRequest {
  source_keys: string[];
}

export interface BulkPointKeysRequest {
  source_keys: string[];
  collection: string;
  batch_size?: number;
}

export interface BackfillPointsRequest {
  collection: string;
  batch_size?: number;
}

export interface SetPayloadRequest {
  source_keys: string[];
  collection: string;
  payload: Record<string, any>;
}

export interface DeletePayloadRequest {
  source_keys: string[];
  collection: string;
  payload_keys: string[];
}

export interface ClearPayloadRequest {
  source_keys: string[];
  collection: string;
}

export interface CountRequest {
  collection: string;
  filter?: any;
}

export interface FacetsRequest {
  collection: string;
  filter?: any;
  field: string;
  limit?: number;
}

export interface DenseSearchRequest {
  collection: string;
  filter?: any;
  vector_name?: any;
  embedding: number[];
  limit?: number;
}

export interface CandidateSearchRequest {
  collection: string;
  filter?: any;
  vector_name?: any;
  embedding: number[];
  limit?: number;
  candidate_point_ids: number[];
}

export interface RecommendRequest {
  collection: string;
  positive_point_ids?: any;
  negative_point_ids?: number[];
  positive_vectors?: any;
  negative_vectors?: number[][];
  limit?: number;
}

export interface ContextPointDiscoveryRequest {
  collection: string;
  context_point_ids: number[];
  limit?: number;
}

export interface RegisterModelVersionRequest {
  collection: string;
  model_name: string;
  model_version: string;
  dimensions: number;
  metric: 'l2' | 'inner_product' | 'cosine' | 'l1';
}

export interface CreateEmbeddingMigrationRequest {
  collection: string;
  source_model_name: string;
  source_model_version: string;
  target_model_name: string;
  target_model_version: string;
  total_points: number;
}

export interface UpdateEmbeddingMigrationRequest {
  processed_points: number;
  status: 'planned' | 'running' | 'completed' | 'failed';
}

export interface RawVectorSearchRequest {
  query: number[];
  point_ids: number[];
  vectors: number[][];
  metric: 'l2' | 'inner_product' | 'cosine' | 'l1';
  limit?: number;
}

export interface GroupedSearchRequest {
  collection: string;
  vector_name?: any;
  embedding: number[];
  group_by: string;
  group_limit?: number;
  limit?: number;
}

export interface RecallCheckRequest {
  collection: string;
  filter?: any;
  vector_name?: any;
  embedding: number[];
  limit?: number;
  minimum_recall?: number;
}

export interface TextHybridSearchRequest {
  collection: string;
  vector_name?: any;
  embedding: number[];
  query: string;
  limit?: number;
}

export interface GraphStart {
  schema_name: string;
  table: string;
  id: string;
}

export interface GraphFirstSearchRequest {
  collection: string;
  filter?: any;
  vector_name?: any;
  embedding: number[];
  limit?: number;
  max_depth?: number;
  graph_limit?: number;
  relationship_types?: string[];
  direction?: ContextGraphDirection;
  start: GraphStart;
}

export interface VectorFirstSearchRequest {
  collection: string;
  filter?: any;
  vector_name?: any;
  embedding: number[];
  limit?: number;
  max_depth?: number;
  graph_limit?: number;
  relationship_types?: string[];
  direction?: ContextGraphDirection;
  context_limit?: number;
}

export interface RankFusionWeights {
  context?: number;
  graph?: number;
}

export interface RankFusionSearchRequest {
  collection: string;
  filter?: any;
  vector_name?: any;
  embedding: number[];
  limit?: number;
  max_depth?: number;
  graph_limit?: number;
  relationship_types?: string[];
  direction?: ContextGraphDirection;
  start: GraphStart;
  context_limit?: number;
  weights?: RankFusionWeights;
}

export interface JointWeights {
  semantic?: number;
  lexical?: number;
  graph?: number;
}

export interface JointSearchRequest {
  collection: string;
  filter?: any;
  vector_name?: any;
  embedding: number[];
  limit?: number;
  max_depth?: number;
  graph_limit?: number;
  relationship_types?: string[];
  direction?: ContextGraphDirection;
  query?: any;
  starts?: GraphStart[];
  context_limit?: number;
  seed_limit?: number;
  traversal_limit?: number;
  weights?: JointWeights;
}

export interface ContextQueryPlan {
  kind: 'nearest' | 'sparse_nearest' | 'full_text' | 'late_interaction' | 'recommend' | 'discover' | 'lookup' | 'prefetch' | 'weight' | 'score_threshold' | 'formula' | 'rerank';
  vector?: any;
  vector_name?: any;
  filter?: any;
  text_query?: any;
  text_column?: any;
  query_vectors?: any;
  candidates_per_query?: any;
  positive_point_ids?: any;
  negative_point_ids?: any;
  context_point_ids?: any;
  point_ids?: any;
  branches?: any;
  branch?: any;
  weight?: any;
  min_score?: any;
  max_score?: any;
  formula?: any;
  limit?: any;
}

export interface QueryExecuteRequest {
  collection: string;
  plan: ContextQueryPlan;
}

export interface QueryExplainRequest {
  collection: string;
  text_column: string;
}

export interface ErrorEnvelope {
  request_id: string;
  error: ErrorBody;
}

export interface CapabilitiesResponse {
  request_id: string;
  contract_version: 'context.v1';
  product_status: 'preview';
  pgcontext_compatibility: PgContextCompatibilityCapabilities;
  runtime: RuntimeCapabilities;
  setup: boolean;
  setup_blocker: any;
  setup_blocker_message?: any;
  dense_search: boolean;
  dense_search_blocker: any;
  dense_search_blocker_message?: any;
  point_scroll: boolean;
  point_scroll_blocker: any;
  point_scroll_blocker_message?: any;
  count: boolean;
  count_blocker: any;
  count_blocker_message?: any;
  facets: boolean;
  facets_blocker: any;
  facets_blocker_message?: any;
  grouped_search: boolean;
  grouped_search_blocker: any;
  grouped_search_blocker_message?: any;
  recall_check: boolean;
  recall_check_blocker: any;
  recall_check_blocker_message?: any;
  text_hybrid: boolean;
  text_hybrid_blocker: any;
  text_hybrid_blocker_message?: any;
  graph_first: boolean;
  graph_first_blocker: any;
  graph_first_blocker_message?: any;
  vector_first: boolean;
  vector_first_blocker: any;
  vector_first_blocker_message?: any;
  rank_fusion: boolean;
  rank_fusion_blocker: any;
  rank_fusion_blocker_message?: any;
  joint: boolean;
  joint_blocker: any;
  joint_blocker_message?: any;
  ranked_search_cursor: false;
  max_dimensions: number;
  max_search_limit: number;
  max_context_limit: number;
  max_graph_limit: number;
  max_joint_seed_limit: number;
  max_joint_traversal_limit: number;
  max_graph_depth: number;
  max_relationship_types: number;
  max_result_columns: number;
  max_filter_bytes: number;
  max_filter_depth: number;
  max_filter_nodes: number;
  max_filter_values: number;
  max_values_per_match: number;
  max_reconcile_point_keys: number;
  max_point_keys_per_operation: number;
}

export interface DiscoveryResponse {
  request_id: string;
  candidates: DiscoveryCandidate[];
}

export interface ContextOnboardingResponse {
  request_id: string;
  status: any;
  compatibility_generation: number;
  candidates: ContextOnboardingCandidate[];
  offer_acknowledged: boolean;
  selected_vector_configuration_id: any;
  completed_collection_id: any;
  evaluated_at: any;
  updated_at: any;
}

export interface PreflightResponse {
  request_id: string;
  eligible: boolean;
  classification: any;
  normalized_request: Record<string, any>;
  source_identity: Record<string, string>;
  checks: PreflightCheck[];
  blockers: PreflightBlocker[];
  warnings: Record<string, any>[];
  planned_actions: Record<string, any>[];
  ownership: PreflightOwnership;
}

export interface ContextCollection {
  id: string;
  project_id: string;
  name: string;
  is_default: boolean;
  status: any;
  schema_name: string;
  table_name: string;
  source_key_column: string;
  source_key_type: string;
  source_mode: ContextSourceMode;
  owns_source_table: boolean;
  default_vector_name: string;
  vectors: ContextCollectionVector[];
  max_search_limit: number;
  text_column: any;
  result_columns: string[];
  filter_columns: string[];
  jsonb_filter_paths: Record<string, any>[];
  point_reconciliation_status: any;
  mapped_point_count: any;
  last_reconciled_at: any;
  last_error_code: any;
  last_error_stage: any;
  created_at: string;
  updated_at: string;
}

export interface CollectionListResponse {
  request_id: string;
  collections: ContextCollection[];
  next_cursor: any;
  has_more: boolean;
}

export interface CollectionGetResponse {
  request_id: string;
  collection: ContextCollection;
  deletion_plan: DeletionPlan;
}

export interface CollectionAliasResponse {
  request_id: string;
  alias: CollectionAlias;
}

export interface CollectionAliasListResponse {
  request_id: string;
  aliases: CollectionAlias[];
}

export interface CollectionAliasDropResponse {
  request_id: string;
  alias_name: string;
  dropped: boolean;
}

export interface PgContextCollectionInfoResponse {
  request_id: string;
  collection: PgContextCollectionInfo;
}

export interface CollectionLimitsResponse {
  request_id: string;
  collection_name: string;
  limits: CollectionLimits;
}

export interface CollectionVectorsResponse {
  request_id: string;
  collection_name: string;
  vectors: PgContextVectorMetadata[];
}

export interface VectorConfigureResponse {
  request_id: string;
  vector: PgContextVectorMetadata;
}

export interface CollectionStatusResponse {
  request_id: string;
  collection_id: string;
  collection_name: string;
  status: any;
  serving_status: any;
  vectors: ContextCollectionVector[];
  point_reconciliation_status: any;
  mapped_point_count: any;
  last_reconciled_at: any;
  active_operation: any;
  last_error_code: any;
  last_error_stage: any;
  updated_at: string;
}

export interface VerificationResponse {
  request_id: string;
  collection_id: string;
  collection_name: string;
  verified: boolean;
  checked_at: string;
  checks: VerificationCheck[];
}

export interface DiagnosticsResponse {
  request_id: string;
  collection_id: string;
  collection_name: string;
  overall_status: any;
  checked_at: string;
  checks: DiagnosticCheck[];
  recommended_actions: RecommendedAction[];
}

export interface FilterListResponse {
  request_id: string;
  collection_id: string;
  filters: FilterRegistration[];
}

export interface PointStatusResponse {
  request_id: string;
  collection_id: string;
  status: any;
  mapped_point_count: any;
  last_reconciled_at: any;
  last_error_code: any;
  last_error_stage: any;
  active_operation: any;
}

export interface PointScrollResponse {
  request_id: string;
  collection_id: string;
  points: PointMapping[];
  next_cursor: any;
  has_more: boolean;
}

export interface PointMutationResponse {
  request_id: string;
  collection_id: string;
  processed: number;
  inserted: number;
  reactivated: number;
  already_active: number;
  deleted: number;
  already_absent: number;
}

export interface PointBatchResponse {
  request_id: string;
  batches: PointBatchProgress[];
}

export interface PayloadMutationResponse {
  request_id: string;
  results: PayloadMutationResult[];
}

export interface PgContextScoredResponse {
  request_id: string;
  results: PgContextScoredPoint[];
}

export interface IndexStatusResponse {
  request_id: string;
  rows: IndexStatusRow[];
}

export interface IndexDiagnosticsResponse {
  request_id: string;
  rows: IndexDiagnosticsRow[];
}

export interface IndexMemoryEstimateResponse {
  request_id: string;
  rows: IndexMemoryEstimateRow[];
}

export interface IndexAdvisorResponse {
  request_id: string;
  rows: IndexAdvisorRow[];
}

export interface OptimizationStatusResponse {
  request_id: string;
  rows: OptimizationStatusRow[];
}

export interface VacuumAdviceResponse {
  request_id: string;
  rows: VacuumAdviceRow[];
}

export interface TelemetryResponse {
  request_id: string;
  rows: TelemetryRow[];
}

export interface ModelVersionsResponse {
  request_id: string;
  rows: ModelVersionRow[];
}

export interface EmbeddingMigrationsResponse {
  request_id: string;
  rows: EmbeddingMigrationRow[];
}

export interface RawVectorSearchResponse {
  request_id: string;
  results: RawVectorSearchResult[];
}

export interface QueryCohortStatsResponse {
  request_id: string;
  rows: QueryCohortStatsRow[];
}

export interface QueryExecutionStatsResponse {
  request_id: string;
  rows: QueryExecutionStatsRow[];
}

export interface ContextOperation {
  id: string;
  collection_id: any;
  kind: ContextOperationKind;
  status: any;
  stage: string;
  processed_units: number;
  total_units: any;
  attempts: number;
  retry_until: string;
  error: any;
  created_at: string;
  started_at: any;
  finished_at: any;
  updated_at: string;
}

export interface OperationEnvelope {
  request_id: string;
  operation: ContextOperation;
}

export interface OperationListResponse {
  request_id: string;
  operations: ContextOperation[];
  next_cursor: any;
  has_more: boolean;
}

export interface CountResponse {
  request_id: string;
  collection_id: string;
  collection_name: string;
  count: number;
}

export interface FacetsResponse {
  request_id: string;
  collection_id: string;
  collection_name: string;
  field: string;
  facets: FacetValue[];
}

export interface RankedResponse {
  request_id: string;
  collection: RankedCollection;
  mode: any;
  results: any[];
  warnings: ContextWarning[];
}

export interface QueryExecutionResponse {
  request_id: string;
  collection: RankedCollection;
  results: QueryExecutionResult[];
}

export interface QueryExplainResponse {
  request_id: string;
  collection: RankedCollection;
  rows: QueryExplainRow[];
}

export interface LexicalLane {
  rank: number;
  score: number;
}

export interface JointGraphLane {
  rank: number;
  depth: number;
  relationships: Relationship[];
}

export interface JointScoreBreakdown {
  semantic: number;
  lexical: number;
  graph: number;
  total: number;
}

export interface JointFusionWeights {
  semantic: number;
  lexical: number;
  graph: number;
}

export interface JointFusionMetadata {
  method: 'joint_weighted_rrf';
  k: 60;
  weights: JointFusionWeights;
}

export interface JointTrace {
  semantic_candidates: number;
  lexical_candidates: number;
  explicit_seeds: number;
  retrieval_seeds: number;
  retained_seeds: number;
  graph_candidates: number;
  combined_candidates: number;
  rescored_candidates: number;
}

export interface ContextJointResult {
  point_id: number;
  source: ContextSourceIdentity;
  rank: number;
  score: number;
  score_kind: 'joint_weighted_rrf';
  metric?: null;
  properties: Record<string, any>;
  group_value?: any;
  group_rank?: any;
  introduced_by_graph: boolean;
  baseline_rank: any;
  rank_lift: any;
  context: ContextLane;
  lexical: any;
  graph: any;
  score_breakdown: JointScoreBreakdown;
}

export interface ContextJointResponse {
  request_id: string;
  collection: RankedCollection;
  mode: 'joint';
  results: ContextJointResult[];
  fusion: JointFusionMetadata;
  trace: JointTrace;
  warnings: ContextWarning[];
}

export interface RecallCheckResponse {
  request_id: string;
  collection_id: string;
  collection_name: string;
  exact_count: number;
  candidate_count: number;
  intersection_count: number;
  recall: number;
  minimum_recall: number;
  status: any;
}

export interface RuntimeCapabilities {
  postgres_major: number;
  pgcontext_version: any;
  pgcontext_source_commit: any;
  pgvector_installed: boolean;
  pgcontext_installed: boolean;
  pgvector_version?: any;
  pgvector_schema?: any;
  pgcontext_pgvector_version?: any;
  same_column_bridge?: boolean;
}

export interface PgContextCompatibilityCapabilities {
  target_version: '0.2.0';
  stable_items: number;
  aligned: number;
  managed_equivalent: number;
  partial: number;
  sql_only: number;
  deferred: number;
  missing_sdk: 0;
}

export interface DiscoveryReason {
  code: string;
  message: string;
  field?: any;
}

export interface DiscoverySource {
  schema_name: string;
  table_name: string;
  source_key_column: string;
  source_key_type: string;
}

export interface DiscoveryVector {
  column_name: string;
  type_owner: string;
  dimensions: any;
  nullable: boolean;
}

export interface DiscoveryColumn {
  column_name: string;
  data_type: string;
  nullable: boolean;
  ordinal_position: number;
}

export interface DiscoveryCandidate {
  classification: any;
  source: DiscoverySource;
  vectors: DiscoveryVector[];
  columns?: DiscoveryColumn[];
  reasons: DiscoveryReason[];
}

export interface ContextOnboardingCandidate {
  vector_configuration_id: string;
  name: string;
  schema_name: string;
  table_name: string;
  row_id_column: string;
  embedding_column: string;
  dimensions: number;
  metric: ContextMetric;
  is_default: boolean;
}

export interface PreflightCheck {
  code: string;
  status: string;
  message: string;
}

export interface PreflightBlocker {
  code: string;
  message: string;
  field?: any;
}

export interface PreflightOwnership {
  source_table: string;
  vector_column: string;
  index: string;
}

export interface ContextCollectionVector {
  id: string;
  name: string;
  column_name: string;
  is_default: boolean;
  owns_vector_column: boolean;
  vector_type_owner?: 'pgcontext' | 'pgvector';
  dimensions: number;
  metric: ContextMetric;
  index_kind: ContextIndexKind;
  index_name: any;
  owns_index: boolean;
  index_status: any;
  last_error_code: any;
  last_error_stage: any;
  created_at: string;
  updated_at: string;
}

export interface DeletionPlan {
  pgcontext_collection: string;
  drop_owned_indexes: string[];
  preserve_source_table: string;
  preserve_source_columns: string[];
  preserve_indexes: string[];
}

export interface CollectionAlias {
  alias_name: string;
  collection_name: string;
}

export interface PgContextCollectionInfo {
  collection_id: number;
  collection_name: string;
  owner_name: string;
  table_schema: any;
  table_name: any;
}

export interface CollectionLimits {
  strict_mode: boolean;
  max_dimensions: any;
  max_vectors: any;
  max_points: any;
  max_filter_nodes: any;
  max_search_limit: any;
  max_candidate_budget: any;
  query_timeout_ms: any;
  max_index_memory_bytes: any;
}

export interface PgContextVectorMetadata {
  collection_name: string;
  vector_name: string;
  table_schema: string;
  table_name: string;
  vector_column: string;
  dimensions: number;
  metric: string;
  hnsw_options: Record<string, any>;
  quantization_options: Record<string, any>;
  status: string;
}

export interface ContextOperationFailure {
  code: string;
  variant?: any;
  message: string;
  details: Record<string, any>;
  http_status: number;
}

export interface VerificationCheck {
  name: string;
  status: any;
  code: any;
  message: string;
}

export interface DiagnosticCheck {
  name: string;
  status: any;
  code: any;
  message: string;
  expected: any;
  actual: any;
  count: any;
}

export interface RecommendedAction {
  action: ContextRecommendedAction;
  message: string;
}

export interface FilterRegistration {
  key: string;
  kind: ContextFilterKind;
  column: string;
  path: any;
}

export interface PointMapping {
  point_id: number;
  source_key: string;
}

export interface PointBatchProgress {
  batch_number: number;
  processed_count: number;
  inserted_count?: any;
  reactivated_count?: any;
  deleted_count?: any;
  missing_count?: any;
}

export interface PayloadMutationResult {
  source_key: string;
  updated: boolean;
}

export interface PgContextScoredPoint {
  point_id: number;
  source_key: string;
  score: number;
}

export interface IndexStatusRow {
  index_schema: string;
  index_name: string;
  table_schema: string;
  table_name: string;
  access_method: string;
  is_valid: boolean;
  is_ready: boolean;
  is_live: boolean;
  status: string;
}

export interface IndexDiagnosticsRow {
  index_schema: string;
  index_name: string;
  table_schema: string;
  table_name: string;
  access_method: string;
  status: string;
  context_error: any;
  sqlstate: any;
  repair_advice: string;
}

export interface IndexMemoryEstimateRow {
  index_schema: string;
  index_name: string;
  table_schema: string;
  table_name: string;
  access_method: string;
  estimated_rows: number;
  dimensions: number;
  vector_bytes: number;
  link_bytes: number;
  total_bytes: number;
  status: string;
}

export interface IndexAdvisorRow {
  collection_name: string;
  filter_key: any;
  column_name: any;
  recommendation: string;
  detail: string;
  suggested_sql: any;
}

export interface OptimizationStatusRow {
  collection_name: string;
  table_schema: any;
  table_name: any;
  has_source_table: boolean;
  source_table_exists: boolean;
  registered_vectors: number;
  active_points: number;
  filter_fields: number;
  hnsw_indexes: number;
  status: string;
}

export interface VacuumAdviceRow {
  index_schema: string;
  index_name: string;
  table_schema: string;
  table_name: string;
  access_method: string;
  estimated_index_tuples: number;
  index_pages: number;
  dead_table_tuples: number;
  status: string;
}

export interface TelemetryRow {
  collection_name: string;
  table_schema: any;
  table_name: any;
  has_source_table: boolean;
  source_table_exists: boolean;
  registered_vectors: number;
  active_points: number;
  deleted_points: number;
  filter_fields: number;
  hnsw_indexes: number;
  status: string;
}

export interface ModelVersionRow {
  collection_name: string;
  model_name: string;
  model_version: string;
  dimensions: number;
  metric: string;
  is_active: boolean;
}

export interface EmbeddingMigrationRow {
  migration_id: number;
  collection_name: string;
  source_model: string;
  source_version: string;
  target_model: string;
  target_version: string;
  status: string;
  total_points: number;
  processed_points: number;
}

export interface RawVectorSearchResult {
  point_id: number;
  score: number;
}

export interface QueryCohortStatsRow {
  collection_name: string;
  cohort: string;
  query_kind: string;
  query_count: number;
  total_results: number;
  total_candidates: any;
  total_rows_rechecked: number;
  total_rows_pruned: number;
  avg_recall_threshold: any;
  avg_recall_achieved: any;
  latency_bucket: string;
  lifecycle_state: string;
  avg_latency_ms: number;
  status: string;
}

export interface QueryExecutionStatsRow {
  collection_name: string;
  query_kind: string;
  strategy: string;
  query_count: number;
  total_visits: number;
  total_filter_candidates: number;
  total_candidates: number;
  total_rechecks: number;
  total_stages: number;
  total_expansions: number;
  completion: string;
  latency_bucket: string;
  lifecycle_state: string;
  avg_latency_ms: number;
}

export interface FacetValue {
  value: string;
  count: number;
}

export interface ContextSourceIdentity {
  schema_name: string;
  table: string;
  id: string;
}

export interface ContextLane {
  rank: number;
  score: number;
  metric: ContextMetric;
}

export interface Relationship {
  type: string;
  direction: any;
  from_: ContextSourceIdentity;
  to: ContextSourceIdentity;
}

export interface GraphLane {
  rank: any;
  depth: any;
  relationships: Relationship[];
}

export interface FusionMetadata {
  method: 'weighted_rrf';
  k: 60;
  context_weight: number;
  graph_weight: number;
}

export interface ContextSearchResult {
  point_id: number;
  source: ContextSourceIdentity;
  rank: number;
  score: number;
  score_kind: any;
  metric?: any;
  properties: Record<string, any>;
  group_value?: any;
  group_rank?: any;
}

export interface ContextTextHybridResult {
  point_id: number;
  source: ContextSourceIdentity;
  rank: number;
  score: number;
  score_kind: 'rrf';
  metric?: any;
  properties: Record<string, any>;
  group_value?: any;
  group_rank?: any;
  rrf_k: 60;
}

export interface ContextGraphHybridResult {
  point_id: number;
  source: ContextSourceIdentity;
  rank: number;
  score: number;
  score_kind: any;
  metric?: any;
  properties: Record<string, any>;
  group_value?: any;
  group_rank?: any;
  mode: 'graph_first' | 'vector_first' | 'rank_fusion';
  context: any;
  graph: any;
  fusion: any;
}

export interface ContextWarning {
  code: string;
  message: string;
  details: Record<string, any>;
}

export interface RankedCollection {
  id: string;
  name: string;
}

export interface QueryExecutionResult {
  point_id: number;
  source_key: string;
  score: number;
}

export interface QueryExplainRow {
  stage: string;
  detail: string;
  branch: any;
  strategy: string;
  status: string;
  estimated_candidates: any;
  candidate_budget: any;
}

export interface ContextRequest {
}

export interface ContextResponse {
}
